name: GitHub Classroom Autograding
on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TESTS_RESULTS: ${{ steps.autograding.outputs.result }}
        with:
          runners: logic-verification
  
  autograding:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: logic-verification
        id: logic-verification
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Logic Verification
          setup-command: npm install
          command: npm test
          timeout: 10
          max-score: 100
