name: GitHub Classroom Autograding
on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: logic-verification
        id: logic-verification
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Logic Verification
          setup-command: npm install
          command: npm test
          timeout: 10
          max-score: 100
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          LOGIC-VERIFICATION_RESULTS: "${{steps.logic-verification.outputs.result}}"
        with:
          runners: logic-verification
